steps:
  # Step 1 - Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/eighth-orbit-391014/devi-devops-app:$BUILD_ID', '.']

  # Step 2 - Push to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eighth-orbit-391014/devi-devops-app:$BUILD_ID']

  # Step 3 - Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/devops-app'
      - 'devops-app=gcr.io/eighth-orbit-391014/devi-devops-app:$BUILD_ID'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=devops-gke-cluster'

images:
  - 'gcr.io/eighth-orbit-391014/devi-devops-app:$BUILD_ID'

timeout: '1200s'
